GET http://localhost:5000/v1/users/trash/api_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGFuZyBkdXkga2hhbmgiLCJlbWFpbCI6ImRhbmdraGFuaC5kZXZAZ21haWwuY29tIiwicGFzc3dvcmQiOiIxMzEyMjAwMiIsImlhdCI6MTY1NjQ4NTc4OH0.blulU9322ovspUzcS482J3v9muTEGvJtnVzGrdjd9Vw
