GET http://localhost:5000/v1/books/page=1/limit=4/api_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGFuZyBkdXkga2hhbmgiLCJlbWFpbCI6ImRhbmdraGFuaC5kZXZAZ21haWwuY29tIiwicGFzc3dvcmQiOiIxMzEyMjAwMiIsImlhdCI6MTY1NjU4MTc5OX0.dOVqKZ69BXCWlfUhe9nx7cohw3toILnSFAtfv-Ea49U